global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Evidently AI Drift Monitoring
  - job_name: 'evidently-drift-monitoring'
    static_configs:
      - targets: ['monitoring:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    # This scrapes metrics from the monitoring container running monitor_drift.py 