name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov python-dotenv

      - name: Create .env.test file for tests
        run: |
          echo "MLFLOW_TRACKING_URI=http://dummy-mlflow:5000" >> .env.test
          echo "S3_BUCKET_NAME=dummy-bucket" >> .env.test
          echo "SUPABASE_URL=https://dummy.supabase.co" >> .env.test
          echo "SUPABASE_KEY=dummy-key" >> .env.test

      - name: Lint and Test
        env:
          ENV_FILE: .env.test
        run: |
          cp $ENV_FILE .env
          bash run_tests.sh

      - name: Login to Prefect Cloud
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: prefect cloud login --key ${{ secrets.PREFECT_KEY }} --workspace "lamel-mo/default"

      - name: Create .env.deploy file for deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "SOURCE_REPO=https://github.com/${{ github.repository }}.git" > .env.deploy
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> .env.deploy

      - name: Deploy Prefect Flows
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GIT_COMMIT_HASH: ${{ github.sha }}
          SOURCE_REPO: https://github.com/${{ github.repository }}.git
        run: |
          cp .env.deploy .env
          python prefect_deployment.py
